service: chrome-serp

package:
  individually: true
useDotenv: true
provider:
  name: aws
  versionFunctions: false
  runtime: nodejs18.x
  region: us-east-1
  memorySize: 2048
  timeout: 240
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "*"
  stage: ${env:NODE_ENV, 'dev'}
  environment:
    STAGE: ${env:NODE_ENV, 'dev'}
    IS_LOCAL_DEVELOPMENT: ${env:IS_LOCAL_DEVELOPMENT, ''}
    LOCAL_PATH: ${env:LOCAL_PATH, ''}

functions:
  scrape:
    handler: puppeteer/scrape.handler
    events:
      - schedule: rate(8 days)

    layers:
      - arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:38
    package:
      patterns:
        - '!./**'
        - 'puppeteer/**'
        - 'node_modules/**'
        - 'package.json'

plugins:
  - serverless-offline

