name: Deploy to AWS using Serverless

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js v18
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install production dependencies
        run: |
          npm ci --only=production

      - name: Deploy using Serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME }}
          HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
          CERTIFICATE_ARN: ${{ secrets.CERTIFICATE_ARN }}
        run: |
          npx serverless deploy
