name: Deploy to AWS using Serverless

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install production dependencies
        run: |
          npm install serverless -g
          npm install serverless-layer-organizer -g
          npm ci --only=production

      - name: Deploy using Serverless
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          USER_LOGIN: ${{ secrets.USER_LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          serverless deploy
